const translations = {
  en: {
    // Navbar
    'nav.services': 'Services',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.getQuote': 'Request Quote',

    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive solutions in fuel and lubricant distribution',
    'services.webApps.title': 'Fuel Distribution',
    'services.webApps.description': 'We distribute a wide range of premium fuels from recognized oil companies, guaranteeing the highest quality standards.',
    'services.responsive.title': 'Lubricants',
    'services.responsive.description': 'High-tech Mobil Super™ lubricants that provide superior protection for all types of vehicles with maximum performance and fuel economy.',
    'services.frontend.title': 'Urea Solution',
    'services.frontend.description': 'Automotive urea additive formulated for vehicles with selective catalytic reduction to minimize emissions of polluting gases.',
    'services.backend.title': 'Satellite Monitoring',
    'services.backend.description': 'We ensure full traceability of our products from loading at recognized oil companies to delivery to each customer.',
    'services.database.title': 'Lubricant Analysis',
    'services.database.description': 'We provide the necessary knowledge to better understand the condition of your company\'s lubricants and equipment.',
    'services.support.title': 'Technical Support',
    'services.support.description': 'Planned engineering service and technical advice for all our products and solutions.',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team for more information',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.company': 'Company',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Your message has been sent successfully!',
    'contact.info.title': 'Our Locations',
    'contact.info.location': 'Main Office',
    'contact.info.address': 'AV. CHAMPAGNAT 3490, MAR DEL PLATA',
    'contact.info.phone': 'Phone',
    'contact.info.phoneNumbers': '2236015815',
    'contact.info.email': 'Email',
    'contact.info.emails': 'INFO@PMDP.COM.AR',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Friday',
    'contact.hours.weekdayHours': '8:00 AM - 2:00 PM',
  },
  es: {
    // Navbar
    'nav.services': 'Servicios',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.getQuote': 'Cotización',

    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones integrales en distribución de combustibles y lubricantes',
    'services.webApps.title': 'Distribución de Combustibles',
    'services.webApps.description': 'Comercializamos una amplia gama de combustibles premium de petroleras reconocidas, garantizando los más altos estándares de calidad.',
    'services.responsive.title': 'Lubricantes',
    'services.responsive.description': 'Lubricantes Mobil Super™ de alta tecnología que brindan superprotección para todo tipo de vehículos con máximo rendimiento y economía de combustible.',
    'services.frontend.title': 'Solución de Urea',
    'services.frontend.description': 'Aditivo de urea automotriz formulado para vehículos con reducción catalítica selectiva para minimizar emisiones de gases contaminantes.',
    'services.backend.title': 'Monitoreo Satelital',
    'services.backend.description': 'Aseguramos la trazabilidad completa de nuestros productos desde la carga en petroleras reconocidas hasta la entrega a cada cliente.',
    'services.database.title': 'Análisis de Lubricantes',
    'services.database.description': 'Brindamos el conocimiento necesario para comprender mejor el estado de los lubricantes y equipos de su empresa.',
    'services.support.title': 'Soporte Técnico',
    'services.support.description': 'Servicio de ingeniería planeado y asesoramiento técnico para todos nuestros productos y soluciones.',

    // Contact
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Comuníquese con nuestro equipo para más información',
    'contact.form.title': 'Envíenos un mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Teléfono',
    'contact.form.company': 'Empresa',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Su mensaje ha sido enviado con éxito!',
    'contact.info.title': 'Nuestras Sucursales',
    'contact.info.location': 'Oficina Principal',
    'contact.info.address': 'AV. CHAMPAGNAT 3490, MAR DEL PLATA',
    'contact.info.phone': 'Teléfono',
    'contact.info.phoneNumbers': '2236015815',
    'contact.info.email': 'Email',
    'contact.info.emails': 'INFO@PMDP.COM.AR',
    'contact.hours.title': 'Horario de Atención',
    'contact.hours.weekdays': 'Lunes - Viernes',
    'contact.hours.weekdayHours': '8:00 AM - 2:00 PM',
  }
};