// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpbckkaxydcnopbwhrvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwYmNra2F4eWRjbm9wYndocnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjgyNjIsImV4cCI6MjA1ODAwNDI2Mn0.OFzBgrS3Dxd-_Rz5csP2Zpsz6e9Z8du-QhIVvEehDQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);